## Pass an error when occured

```python
try:
  # foo
except:
  pass
```
